about_me/about_me/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
]

about_me/main/urls.py
from django.urls import path

from .views import index, profiles_by_skill


app_name = 'main'

urlpatterns = [
    path('', index, name='main_page'),
    path('skill/<slug:slug>/', profiles_by_skill, name='skill_page')
]

about_me/main/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

MAX_LEN_FOR_STR = 50


class Skill(models.Model):
    """Модель навыка."""
    name = models.CharField(max_length=218,
                            verbose_name="Название навыка",
                            )
    value = models.IntegerField(validators=[
                            MinValueValidator(1, "Минимальное зачение-1"),
                            MaxValueValidator(10, "Максимальное значение-10"),
                            ],
                            default=1,
                            verbose_name="Важность навыка",
                            help_text="Значение от 1 до 10",
                            )
    slug = models.SlugField(unique=True,
                            verbose_name="Уникальное имя навыка",
                            max_length=350,
                            )

    class Meta:
        ordering = ("value",)
        verbose_name = "Навык"
        verbose_name_plural = "Навыки"

    def __str__(self):
        return self.name[:MAX_LEN_FOR_STR]


class Profile(models.Model):
    """Модель профиля сотрудника."""
    name = models.CharField(max_length=218,
                            verbose_name="Полное имя",
                            )
    age = models.IntegerField(default=18,
                              verbose_name="Возраст",
                              )
    skill = models.ForeignKey(Skill,
                              on_delete=models.SET_NULL,
                              null=True,
                              related_name="profiles",
                              )
    price = models.PositiveIntegerField('Зарплата',
                                        default=30000,
                                        )

    class Meta:
        ordering = ("name",)
        verbose_name = "Профиль сотрудника"
        verbose_name_plural = "Профили сотрудников"

    def __str__(self):
        return self.name[:MAX_LEN_FOR_STR]

about_me/main/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404

from .models import Profile, Skill


def index(request):
    """Главная страница."""
    template = "index.html"
    profiles = Profile.objects.select_related("skill").all()
    context = {}
    context['profiles'] = profiles
    return render(request, template, context)


def profiles_by_skill(request, slug):
    """Страница с профилями с конкретным скилом."""
    skill = get_object_or_404(Skill, slug=slug)

    # profiles = Profile.objects.filter(skill_id=skill.id)

    profiles = skill.profiles.all()
    context = {}
    context['profiles'] = profiles
    context['skill'] = skill

    return render(request, "skills.html", context)

about_me/main/templates/base.html
{% load static %} 

<!DOCTYPE html> 
<html lang="ru">  
  <head>     
    <meta charset="utf-8"> 
    <meta name="viewport" content="width=device-width, initial-scale=1"> 
    <link rel="icon" href="{%static '/img/fav/favicon.ico' %}" type="image"> 
    <link rel="apple-touch-icon" sizes="180x180" href="{%static '/img/fav/apple-touch-icon.png'%}"> 
    <link rel="icon" type="image/png" sizes="32x32" href="{%static '/img/fav/favicon-32x32.png'%}"> 
    <link rel="icon" type="image/png" sizes="16x16" href="{%static '/img/fav/favicon-16x16.png'%}"> 
    <meta name="msapplication-TileColor" content="#000"> 
    <meta name="theme-color" content="#ffffff"> 
    <link rel="stylesheet" href="{%static '/css/bootstrap.min.css'%}"> 
    <title>
      {% block title %}
      Тут будет title страницы, переопределяется в дочерних шаблонах
      {% endblock %} 
    </title> 
  </head> 
  <body> 

    <header> 
      <nav class="navbar navbar-light" style="background-color: rgb(105, 51, 199)"> 
        <div class="container"> 
          <a class="navbar-brand" href="{% url 'main:main_page' %}"> 
            <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt=""> 
            <span style="color:green">Профили</span>сотрудников>
          </a> 
        </div> 
      </nav>     
    </header>

    <main> 
      {% block content %}
      Основной контент страницы, переопределяемый в дочерних шаблонах 
      {% endblock %} 
    </main> 

    <footer class="border-top text-center py-3">
        {% include 'footer.html' %}   
    </footer> 

  </body> 
</html>  

about_me/main/templates/footer.html
<p> 2023 Copyright <span style="color:green">Профили</span>сотрудников</p>
 

about_me/main/templates/index.html
{% extends 'base.html' %}  

{% block title %} 
  Главная страница проекта
{% endblock %} 

{% block content %} 
  <h1>Главная страница проекта</h1>
  <div class="container py-5">  
    {% for profile in profiles %}
      <article>
        Имя - {{ profile.name }}, Возраст - {{ profile.age }}, Навык - {{ profile.skill }}
      </article>
    {% endfor %}
  </div>   
{% endblock %}

about_me/main/templates/skills.html
{% extends 'base.html' %}  

{% block title %} 
  Сотрудники с навыком {{ skill }}
{% endblock %} 

{% block content %} 
  <h1>Сотрудники с навыком {{ skill.name }}</h1>
  <h4>Важность навыка - {{ skill.value }}
  <div class="container py-5">  
    {% for profile in profiles %}
      <article>
        Имя - {{ profile.name }}, Возраст - {{ profile.age }}, Навык - {{ skill }}
      </article>
    {% endfor %}
  </div>
{% endblock %}  